# 坐标变换

In [60]:
import cv2 as cv
import numpy as np


## 仿射变换

In [61]:
# 缩放测试
op = np.float32([[0, 0], [0, 3], [3, 0]])  # 原点：A, B, C
pt = np.float32([[0, 0], [0, 6], [6, 0]])  # 映射点：A, B, C
M = cv.getAffineTransform(op, pt)  # 变换矩阵
print(M)

# 齐次变换
M = np.insert(M, 2, values=[0, 0, 1], axis=0)  # 升维
print(M)

p = [3, 4, 1]  # 测试单点
p = np.dot(M, p)  # 点乘，内积
print(p)

p = [[3, 4], [4, 5], [1, 1]]  # 测试点集
p = np.dot(M, p)
print(p)


[[2. 0. 0.]
 [0. 2. 0.]]
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]
[6. 8. 1.]
[[ 6.  8.]
 [ 8. 10.]
 [ 1.  1.]]


![affine](affine.png)

In [62]:
# 旋转、平移示例，affine.png
op = np.float32([[10, 20], [10, 10], [18, 20]])  # 原点：A, B, C
pt = np.float32([[18, 40], [28, 40], [18, 48]])  # 映射点：A, B, C
M = cv.getAffineTransform(op, pt)  # 变换矩阵
print(M)


p = np.array([[12, 17.5]], np.float32)  # 测试单点
p = cv.warpAffine(p, M, (1, 1))
print(p)  # 20.5, 42


# 齐次变换
M = np.insert(M, 2, values=[0, 0, 1], axis=0)  # 升维
print(M)

p = [12, 17.5, 1]  # 测试单点
p = np.dot(M, p)  # 点乘，内积
print(p)  # 20.5, 42


[[ 0. -1. 38.]
 [ 1.  0. 30.]]
[[0.]]
[[ 0. -1. 38.]
 [ 1.  0. 30.]
 [ 0.  0.  1.]]
[20.5 42.   1. ]


## 透视变换

https://zhuanlan.zhihu.com/p/599615858

In [64]:
# 旋转、平移示例，affine.png
op = np.float32([[10, 20], [10, 10], [18, 20], [14, 15]])  # 原点：A, B, C, D
pt = np.float32([[18, 40], [28, 40], [18, 48], [23, 44]])  # 映射点：A, B, C, D
M = cv.getPerspectiveTransform(op, pt)  # 变换矩阵，同时会引入误差，亦或输入的映射点错误?
print(M) 


p = [12, 17.5]  # 测试单点
p = cv.perspectiveTransform(np.array([[p]], dtype="float32"), M)
print(p.flatten())  # 20.5, 42，有误差


p = [12, 17.5, 1]  # 测试单点
p = np.dot(M, p)  # 点乘，内积
print(p)  # 20.5, 42，有误差


# 计算法
def cvt_pos(u, v, mat):
    x = (mat[0][0] * u + mat[0][1] * v + mat[0][2]) / (
        mat[2][0] * u + mat[2][1] * v + mat[2][2]
    )
    y = (mat[1][0] * u + mat[1][1] * v + mat[1][2]) / (
        mat[2][0] * u + mat[2][1] * v + mat[2][2]
    )

    return (x, y)


p = [12, 17.5, 1]  # 测试单点
p = cvt_pos(p[0], p[1], M) # 如果使用仿射变换的矩阵，同样没有误差
print(p) 


[[ 1.87500000e-01 -1.17083333e+00  3.84166667e+01]
 [ 1.43750000e+00 -3.33333333e-01  2.97916667e+01]
 [ 1.04166667e-02 -8.33333333e-03  1.00000000e+00]]
[20.606382 42.085106]
[20.17708333 41.20833333  0.97916667]
(20.606382978723403, 42.08510638297873)
